LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
PTERO_RES_PATH := /pterodon

LOCAL_MODULE := pterodon
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)$(PTERO_RES_PATH)

PTERO_RES_GEN := $(intermediates)/pterodon
PTERO_RES := $(LOCAL_PATH)/res/fonts
PTERO_RES += $(LOCAL_PATH)/res/images
PTERO_RES += $(LOCAL_PATH)/res/language
$(PTERO_RES_GEN):
	mkdir -p $(TARGET_RECOVERY_ROOT_OUT)$(PTERO_RES_PATH)
	cp -fr $(PTERO_RES) $(TARGET_RECOVERY_ROOT_OUT)$(PTERO_RES_PATH)

LOCAL_GENERATED_SOURCES := $(PTERO_RES_GEN)
LOCAL_SRC_FILES := pterodon $(PTERO_RES_GEN)
include $(BUILD_PREBUILT)
